metadata:
  namespace: default
  annotations:
    accelerator.apps.tanzu.vmware.com/icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAkFBMVEX/AAD/////u7v/nJz/SUn/fX3/8vL/5ub/Pj7/Z2f/7Oz/qKj/srL/jY3/W1v/ra3/hob/2dn/bW3/mJj/29v/KSn/9/f/wsL/4eH/oKD/TU3/t7f/cHD/y8v/GRn/g4P/U1P/ODj/MDD/pKT/ISH/aGj/WFj/dnb/k5P/Dg7/yMj/RET/0dH/YWH/Gxv/JiaQLqStAAAL/ElEQVR4nO2d63qqOhCGEQu2nrUtHlsPPSitrt7/3W1RIRMyIQQnELr7/VrPgiZ5JTDJZDJxGuVqMnNLrtEptbavreM4P5NS6yyVsOdcNCyz0hIJ/bUT67tdXrW0hH7GtcOrA/RSsBR9kRIGm/vmVHKt4/CaSe5rze6fSRFJCb2o6Z/dALm0c9IaI7cFi350aUnZKErCSdz4ZboPtrYCoOM8px/3IfkZFoStIiT0n0Hr90/gygThiwRN4/QR/Ar/CL9EhIQe3/x5J27mXgLIzEZ7sE51Ybpm0REiD+oYPaRgLV5IdBd9VCYP2Y/3NpER+q9iM09auf8yAB0nXAzxC2T9lIzQwxtaWGT9lIrwixiQrp8SEfqYObhNP0T9lIiQuo9GIuqnNISuAUDH6ZK0jYTQD40Q0nxPSQiPZgCdNUXjKAhnhgAdZ0/QOgJCekPBRODw0CM8fPb7x/F4vPO8YW+/f5x1Bm4XH8zQKBy4g86sud/3hp63O9V87Pc/s2bPtxLKx9BlamWQcF413Fn32BSbhnBqyCro6knd1IKE3arRruoYIxxXjXZV3xRh8KyuvBS96jjjdAhHVZMl0rEXOoR22IpIOvZCh9AOWxHp3gxhq2ouIJln/TZCW2xFJA17oUEoOuark8b8Pz+hAVdMcWks3uQnPFRNxenLAOFj1VCcegYI7bEVkb7pCVuWzCti5bYXuQnNOAyLK7erMSdha3JfNVJKG7dFRhgcmmvLuuhZ4fzxJYfRUBG2ujub7GBa2+VA9SizCINDz64PKK673iHrUUoJp4uxLRNetX4+utJvK0542M9tfPOyFM73Bw3Cu6rbW0gbDcI6vH6i8HkxTtivurGFdPdH+L8iREJ4aqBPDUJbnNt6wl3hf4R10lGD0ER4jHnhDrg/wjpJh3BVdWMLydMg7KmLs1D4ihROaM86mo5wH+pvIsQjqHDCZtWNLaRHDcK3qhtbSPg2HJxwUXVjCwl3EuOEg6obW0iD/IQHk8F45vSKhmhghOltZvXRWy5C31TEbxk6ir5hgdCtm6OUVyhs00gR+jaFIxTTsp1FOKmPI1+uH1dK+Ase4EVjHyec1NNGYIJvY0Lo13PWK9POTxN+2bwOWkTPE44wqOekPltewAj9TdWtMaJLaNiZMPhtXfSid0ZY0zm9SivwHk6rbowRjeC3VLLo+9bM1gya0Ofvo9d7G3TdSSTX7Q6aw4+57AXYHMee1+vtpUUvk1vf++Pd6VamlXfWcrw8aXw8Ht+xGu45ayGZMDVUSkZ528kTvh/Sn048bCw4UhXNwszU6WzWWONnHKF/KyG+OnlVcBAXJJUxW8yTot6FiBK2OULJmigR4UnTdAUahLgPDQojjDegxhB4cg5l0bkJhUB45R7fWwnj/CgxRIAOu5VFaxA2XriilTF3jLCpLBojjCtIIND0FMqidQh5RA1C9dYDhDBZpkkg0E1NyqK1CDlXumnCJASMQXybJ2wAu2WYcJPsM2UQ2J5zZdE44WLW2+2GTVeweeBroyRk9rAIIbMwDALb1gRL8REFOCEr4MhDBsyR5yvKDpjfvYPdOo00inT4+hJDtFkwJoBAAqFg0dkzLAlh+gEwTxAkVETJwyLa2bcizQEQyHIMbFx2KLuUkM8zw7qpWUKwhAEhzBA6cG85m8QUJcznsAZ1QgjRF0VCCJeE/CRrlFFCmNLOyayIhPADEib2wigh/FEBRCDOskgI4RYl1kCjhCEoHUB8ineSE5b1HqLfUiyGhoRwB66wKYxZQhBb44h1UxNCc8HG94YJWXLJGALfqE1B+AqvsMGvacJkVBND4A4jCkK4uA58epBQEfpRwOKf9BNwhJJ1Ndjs7KVFKSE3pGH+M46wtXAFgYkAJAzEO90J/lwfIKEsNgG27mkkCPz2uUbecAqsmls84YSoJMuCM0Yo3aatKBl0Op4wDMPXf9tlh99uxb3rKkIwI1cSypr/FRPKE8opSga/M0cYnCTe3eb6uYoQ/OqFCc/urghiLb2jICGqFv8iqwhBjrTihN8XwoxwWULCdFY3FSGwz8UJI8PvZCaUIyNsfaSLVhGCr5gs9XesIIPAPRFmzd2pCJ/EojUIVR5hyZLEWT8NJzMnIBUhMiZUEQIDdguh4zqZwbJkhKJBIiTMHOc0ncwxoaJomT3ElO6okHC06g0v8pbL5Ue/31/fgWEkJPR7w+u9q2jx8HRr/y5zPLlwGj85Cb3jQ0ofYEbJEU4Oo6mw8pL6KdvyS2lBwvzj0ovCwMksHrZQ05sYPq9nvNnnozrh6poOoWboZDeyhxnBULCBReYWXJ4cvp+WQzi+jGnkbb+VkF/L5h5iKYTb4EIoT1N2MyG3gZwzGaUQRiN/R6ga6mZCLk1uAFtXBuHZk3GBkOWAup2Q29cJJsBlEF72QV0hJNHrtxO+QqsA+4p5wmuowhUCX8YvSMiNorgDVcD/myf0OUJsbOyQEHIbO8ECngYhjBjKTxgvcycQaFZEAsItNPtgt1FRwpx8bFLJIDDDT0DIpTUGdgm6cBTexCKEbPUJQCAIFITc/JWNp+FYIGi1WtOr/+7lpHPkHzuehYtra2Fqp9evQc8BEMg0i4KQy3TAOooyco99eXMcRJd2IYB3AEKInaUYYWqMhLY6B2HyduYgTEXNQc8OrF8MiyIhhMNv9ik0Sgj3rZtYx08Rclusk1Bdo4QcFfsnMjolIdzAUpLxoVlCsGHWkd9VmDAdNQ4NQ+KvMUsIkvEwCMzSFCNMj484j245hOBjyiCw9ScawjksJp5fGCZkVphBYOH6xQiFvQ1wWOMi/4cr+S7kyKgruNRZeEQCgQ693S5T9grp5nTrYNBpNve9oZChaL3q9R6bs8FJb/EzHHsqJeOU75UXb0a47lQYAEVtW4hJAkcC4W/bNjMUCH/D/lioMEgRvqj/pmaapAiX6j+pmY48YdYSXF3FezFsOveASh2OEInaq73uIKFNh3PQ6QkQ1jNrkkrQI2xbwnUaXZw1l73c6B7M2itss2fo1zPZZbaObc7iGz3FsAqF8aw0GZe26plZV6Z+4lgAU8B6JvjCBRJGwUluq54poEWtoWeID5kZ1DtJ1EUhn/ErFRQ0rf/wbZ06JUEIe6pnykQmIWWbGNg1refBCBfNxW3+WOhafV02WPYFNDjPtpOPcipET4DGww/r+TJiWRN/V/7SBcrym56hTg7aes6IdfII1/NrqpMLup6EOvm865mTHV+FwwnRVC7WSyevfj2zRP6d/vD/Iqyn6+3h1xP+/rOCdAiF0IZaSIewnk63v5Pl/l+E66obW0j4Wd04IZadzn5tNQgnXv2yQ292wrEIGYRRUtXZZ41c/OvmAcnikEkYqV2PR7nZTbKSoSo2MwdPMzwNsSX615+NZA8vH+HlUa7sjGTYrFxlJttchOdH2bEtbfvzm+rhaRE27IsLU6f81CW0LW27Oopal9Cy08jv83VRLUK7fKg54ve1CTOToJQudCHtRkLfpkjw9xxmQpvQKtcGfrjxrYQ2RRThi6G3EtoUZpvbVmgRWjRr3OS2FXqE9qzX4GswtxNKkw+Wri91YwsRWhNKHOa3FXqEkoNMytenuqkFCW2xFxq2QpMQTw9SvtT7T4sSWjK/0LEVuoR2RDDo2ApdwpfN5u6keb/ffxgvvWFv33wzG130+Nbc74fecvxwqnMeVb7Z5p9X6BOiMhnJiB+1XTahwblx/nmuXBSEsnPpblZ+V0WGSAhNzTqm6qrVIiE0NBTQMuxS0RAaWfjHl+W1RUTYph+UhyR9lIzQQNz0QF1pLlERkvdToj5KSChJpDaWHUoQ602S60B5AmRekRFiSzffHf+EnrU0tznNZYMBYk9zL7woRUeY7qfbXuwQk0c67q4mfbpPLTaT9VFSwhbcaLt7AeMRmbkEBi84wN+B6jsaiZCQ9dN5N5WPfIQGPRz4m4LFmr6P0hJe/P6bJvKR8MUoqzWSlb09uyfuo8SE/us/7yC5lp6AyKYNo9W7+pxZHZESNtoZ2fL5aSS+R+ksnxSQmDBTLfa93BJ+SVQqkZCduTSmmPflVamEjcX5m0o14syncgkbQbfZLfMBnvQfaS7DbAm3PJ4AAAAASUVORK5CYII=
  invocationCount: 0
  name: spring-cloud-serverless
  title: Spring Cloud Serverless
  description: A simple Spring Cloud Function serverless app
  tags:
    - java
    - spring
    - cloud
    - serverless
    - tanzu
  labels:
    accelerator.apps.tanzu.vmware.com/accelerator: 'true'
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
spec:
  type: service
  owner: default-team
  parameters:
    - definitions: {}
      title: Configure accelerator
      properties:
        projectName:
          title: Name
          description: Provide a name for your new project
          type: string
          default: spring-cloud-serverless
        deploymentType:
          title: Deployment type
          type: string
          enum:
            - workload
            - k8s-simple
            - none
          enumNames:
            - TAP workload
            - Kubernetes deployment and service
            - Skip Kubernetes deployment
          default: workload
          ui:widget: select
        javaVersion:
          title: Java version to use
          type: string
          enum:
            - '1.8'
            - '11'
            - '17'
          enumNames:
            - Java 8
            - Java 11
            - Java 17
          default: '11'
          ui:widget: select
      required:
        - projectName
        - deploymentType
        - javaVersion
      dependencies:
        deploymentType:
          oneOf:
            - properties:
                deploymentType:
                  const: workload
                sourceRepositoryPrefix:
                  title: >-
                    The source image repository prefix to use when pushing the
                    source
                  description: >-
                    The prefix for the source image repository where source can
                    be stored during development
                  type: string
                  default: dev.local
              required: []
            - properties:
                deploymentType:
                  not:
                    anyOf:
                      - const: workload
      ui:order:
        - projectName
        - deploymentType
        - sourceRepositoryPrefix
        - javaVersion
    - title: Git repository
      properties:
        _createGitRepo:
          title: Create Git repo?
          type: boolean
          defaultValue: false
      dependencies:
        _createGitRepo:
          oneOf:
            - properties:
                _createGitRepo: false
            - properties:
                _createGitRepo: true
                bsGitRepository:
                  title: Repository Location
                  type: string
                  ui:field: RepoUrlPicker
                  ui:options:
                    requestUserCredentials:
                      secretsKey: USER_OAUTH_TOKEN
                    allowedHosts:
                      - github.com
                bsGitBranch:
                  title: Default Branch
                  type: string
                  default: main
  steps:
    - id: invoke-accelerator
      name: invoke accelerator engine with provided parameters
      action: vmware:accelerator
      input:
        url: >-
          http://acc-server.accelerator-system.svc.cluster.local/api/accelerators/zip?name=spring-cloud-serverless
        name: spring-cloud-serverless
        options: ${{ parameters }}
    - id: create-repo-github
      name: Create github repo
      if: >-
        ${{ parameters['_createGitRepo'] and
        (parameters.bsGitRepository.startsWith('github.com')) }}
      action: publish:github
      input:
        repoUrl: ${{ parameters.bsGitRepository }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        defaultBranch: ${{ parameters.bsGitBranch }}
    - id: publish-zip
      name: zip files from accelerator and make them available to download
      action: vmware:publish-zip
      input:
        root-dir: ${{ parameters.projectName }}/
  output:
    links:
      - title: Repository
        url: ${{ steps['create-repo-github'].output.remoteUrl }}
      - title: Get zip file
        url: data:application/zip;base64,${{ steps["publish-zip"].output.file }}
        download: ${{ parameters.projectName }}.zip
        acceleratorName: spring-cloud-serverless
        createdGitRepo: ${{ parameters["_createGitRepo"] }}
